### ISSUE TITLE
Using dimminish with argument

### ISSUE THREAD

**Issue by azzamsa** [rememberYou/.emacs.d#3]
I think we can use `:diminish " ⚡"` rather than to have diminish and delight together :)

**Comment by rememberYou** [comment]
Thank you for the suggestion. I always thought I had to use `diminish` if I wanted to hide a particular mode in the mode line and `delight` to replace the string representation of this mode.

By only using `diminish`, I don't always have the expected behavior.

For instance, this doesn't work with my config file:

```
(use-package org :diminish "Θ ") 
```

Indeed, I still have `Org` for the string representation of `org-mode`, but with `delight` I can change it:

```
(use-package org :delight "Θ ") 
```

As a result, I removed `diminish` and kept `delight` in the config file, which allows me to hide a mode and change its representation.

Thank you again for pointing this out to me ☺️

**Comment by azzamsa** [comment]
I never try diminish with org-mode. But the following mode works well for me.

``` elisp
core/aza-ui.el:52:  :diminish beacon-mode
core/aza-ui.el:61:  :diminish which-key-mode
init.el:110:(diminish 'auto-revert-mode)
init.el:149:(use-package diminish
init.el:155:  :diminish " P"
init.el:166:  :diminish " Sp"
init.el:180:  :diminish " Abv"
init.el:191:  :diminish " ⚡"
init.el:202:  :diminish
init.el:211:  :diminish undo-tree-mode
init.el:223:  :diminish " ⛿"
init.el:247:  :diminish super-save-mode
init.el:255:  :diminish rainbow-delimiters-mode)
init.el:260:  :diminish rainbow-mode
init.el:339:  :diminish volatile-highlights-mode
init.el:347:  :diminish anzu-mode
init.el:424:  :diminish " φ"
init.el:483:  :diminish " yas"
init.el:513:  :diminish whitespace-mode
init.el:548:  :diminish
init.el:644:;; diminish
init.el:645:(diminish 'visual-line-mode "Wr")
init.el:646:(diminish 'auto-fill-function "Fl")
modules/aza-org.el:92:(eval-after-load 'org-indent '(diminish 'org-indent-mode))
modules/aza-helm.el:3:  :diminish helm-mode
modules/aza-helm.el:56:  :diminish helm-ag-mode
modules/aza-emacs-lisp.el:59:  '(diminish 'elisp-slime-nav-mode))
modules/aza-emacs-lisp.el:61:  '(diminish 'rainbow-mode))
modules/aza-emacs-lisp.el:63:  '(diminish 'eldoc-mode))
```

**Comment by rememberYou** [comment]
I think `diminish` works for you because you only use it for minor modes. When I test `diminish` **for minors modes**, I see that I can hide and change the string representation of a particular minor mode ([List of major and minor modes](https://www.emacswiki.org/emacs/List_Of_Major_And_Minor_Modes)).

On the other hand, `delight` seems to work **for minors and major mode** and also allows you to hide and modify the string representation of a mode.

I have always had trouble differentiating between the interest of using `diminish` rather than `delight` and vice versa. I read again the [use-package documentation](https://github.com/jwiegley/use-package) about that and it does not help me to understand the difference in this situation ☺️

**Comment by azzamsa** [comment]
> I think diminish works for you because you only use it for minor modes.

Oh thanks. Today I learn.

> I have always had trouble differentiating between the interest of using diminish rather than delight and vice versa. I read again the use-package documentation about that and it does not help me to understand the difference in this situation

Same here. I think our best decision is to use what works best for us :)


By the way. Thanks lot for your config. I learn a lot. Mostly about `:hook` and ob-languages. When I use ob-languages with use-packages, my emacs start blazing fassst.

**Comment by rememberYou** [comment]
You are welcome. Feel free to open new issues and pull requests if necessary.

**Comment by azzamsa** [comment]
Smiling at the start of morning routine. You are really kind. Answering issue politely and describing your thought completely.

Have a great day!
